const sortURL = [ "type", "url" ]
const sortPeople = [ "name", "email", "url" ]

export default [
	{ key: "$schema" },
	{ key: "name" },
	{ key: "displayName" },
	{ key: "version" },
	{ key: "private" },
	{ key: "description" },
	{ key: "categories", sort: true },
	{ key: "keywords", sort: true },
	{ key: "homepage" },
	{ key: "bugs", sort: [ "url", "email" ] },
	{ key: "repository", sort: sortURL },
	{ key: "funding", sort: sortURL },
	{ key: "license", sort: sortURL },
	{ key: "qna" },
	{ key: "author", sort: sortPeople },
	{ key: "maintainers", sort: sortPeople },
	{ key: "contributors", sort: sortPeople },
	{ key: "publisher" },
	{ key: "sideEffects" },
	{ key: "type" },
	{ key: "imports" },
	{ key: "exports" },
	{ key: "main" },
	{ key: "umd:main" },
	{ key: "jsdelivr" },
	{ key: "unpkg" },
	{ key: "module" },
	{ key: "source" },
	{ key: "jsnext:main" },
	{ key: "browser" },
	{ key: "types" },
	{ key: "typesVersions" },
	{ key: "typings" },
	{ key: "style" },
	{ key: "example" },
	{ key: "examplestyle" },
	{ key: "assets" },
	{ key: "bin", sort: true },
	{ key: "man" },
	{ key: "directories", sort: true },
	{ key: "files", sort: true },
	{ key: "workspaces" },
	{ key: "binary", sort: [ "module_name", "module_path", "remote_path", "package_name", "host", ] },
	{ key: "scripts", sort: true },
	{ key: "betterScripts", sort: true },
	{ key: "contributes", sort: true },
	{ key: "activationEvents", sort: true },
	{ key: "husky" },
	{ key: "simple-git-hooks" },
	{ key: "pre-commit" },
	{ key: "commitlint", sort: true },
	{ key: "lint-staged" },
	{ key: "config", sort: true },
	{ key: "nodemonConfig", sort: true },
	{ key: "browserify", sort: true },
	{ key: "babel", sort: true },
	{ key: "browserslist" },
	{ key: "xo", sort: true },
	{ key: "prettier", sort: true },
	{ key: "eslintConfig", sort: true },
	{ key: "eslintIgnore" },
	{ key: "npmpkgjsonlint", sort: true },
	{ key: "remarkConfig", sort: true },
	{ key: "stylelint" },
	{ key: "ava", sort: true },
	{ key: "jest", sort: true },
	{ key: "mocha", sort: true },
	{ key: "nyc", sort: true },
	{ key: "tap", sort: true },
	{ key: "resolutions", sort: true },
	{ key: "dependencies", sort: true },
	{ key: "devDependencies", sort: true },
	{ key: "dependenciesMeta", sort: true },
	{ key: "peerDependencies", sort: true },
	{ key: "peerDependenciesMeta", sort: true },
	{ key: "optionalDependencies", sort: true },
	{ key: "bundledDependencies", sort: true },
	{ key: "bundleDependencies", sort: true },
	{ key: "extensionPack", sort: true },
	{ key: "extensionDependencies", sort: true },
	{ key: "flat" },
	{ key: "engines", sort: true },
	{ key: "engineStrict", sort: true },
	{ key: "languageName" },
	{ key: "os" },
	{ key: "cpu" },
	{ key: "preferGlobal", sort: true },
	{ key: "publishConfig", sort: true },
	{ key: "icon" },
	{ key: "badges", sort: true },
	{ key: "galleryBanner", sort: true },
	{ key: "preview" },
	{ key: "markdown" }
]
